using System;
using System.Collections.Generic;
using System.Text;

namespace Gunz.Packet
{
    enum Command : ushort
    {
        MATCH_LOGIN = 0x3E9,
        MATCH_REQUESTACCOUNTCHARLIST = 0x6A5,
        MATCH_REQUESTCREATECHAR = 0x6AF,
        MATCH_REQUESTDELETECHAR = 0x6B1,
        MATCH_REQUESTSELECTCHAR = 0x6A7,
        MATCH_RESPONSE_RESULT = 0x193,
        MATCH_RESPONSEACCOUNTCHARLIST = 0x6A6,
        MATCH_RESPONSECREATECHAR = 0x6B0,
        MATCH_RESPONSEDELETECHAR = 0x6B2,
        MATCH_RESPONSESELECTCHAR = 0x6A8,
        MATCH_RESPONSELOGIN = 0x3EA,
        MATCH_WHISPER = 0x641,
        MATCHSERVER_REQUESTRECOMMENDEDCHANNEL = 0x4B1,
        MATCHSERVER_RESPONSERECOMMENDEDCHANNEL = 0x4B2,
        NET_PING = 0x142,
        NET_PONG = 0x143,
        RESPONSE_ACCOUNT_IN_USE = 10001,
        RESPONSE_AUTHENTICATION_FAILED = 10005,
        RESPONSE_BANNED = 10004,
        RESPONSE_CHANNEL_CANNOT_ENTER = 30020,
        RESPONSE_CHANNEL_HAS_LEVEL_21_CHARACTER = 30023,
        RESPONSE_CHANNEL_INVALID_LEVEL = 30022,
        RESPONSE_CHANNEL_IS_FULL = 30021,
        RESPONSE_CHARACTER_DOESNT_EXIST = 10110,
        RESPONSE_CHARACTER_IN_CLAN_OR_CASH_ITEMS = 10111,
        RESPONSE_INVALID_PASSWORD = 10000,
        RESPONSE_INVALID_VERSION = 10002,
        RESPONSE_NAME_EMPTY = 10104,
        RESPONSE_NAME_IN_USE = 10100,
        RESPONSE_NAME_INVALID_CHARACTERS = 10101,
        RESPONSE_NAME_TOO_LONG = 10103,
        RESPONSE_NAME_TOO_SHORT = 10102,
        RESPONSE_OK = 0,
        RESPONSE_SERVER_IS_FULL = 10003,
    }
}
